#!/usr/bin/env node
/**
 * 构建客户端 bundle：esbuild 打包 src/client 为 CJS，再包装成 DSH 浏览器端的
 * window.__ModuleLoader__ 模块格式（与 @deepseek-ai/dsh-client-* 一致），
 * 输出到 lib/client.js，供 web 端 /plugins/<id>/client.js 加载。
 */
import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outfile = path.join(root, "lib", "client.js");

// 模块 id 必须等于 npm 包名：DSH client-modules 用 loader entry 的 name（= 包名，
// 见 cordis.patch.yml）作为浏览器端模块 id 和 /plugins/<包名>/client.js 的 URL 段。
const { name: packageName } = JSON.parse(await readFile(path.join(root, "package.json"), "utf8"));

const result = await build({
  entryPoints: [path.join(root, "src", "client", "index.tsx")],
  bundle: true,
  format: "cjs",
  platform: "browser",
  jsx: "automatic",
  minify: false,
  sourcemap: false,
  // 浏览器宿主提供这些模块，bundle 内保持 require(...) 引用。
  external: ["react", "react/jsx-runtime", "react/jsx-dev-runtime", "@deepseek-ai/*"],
  write: false,
});

const body = result.outputFiles[0]?.text ?? "";
await mkdir(path.dirname(outfile), { recursive: true });
await writeFile(
  outfile,
  [
    "// Generated by scripts/build-client.mjs — do not edit.",
    "window.__ModuleLoader__.load({",
    `  id: "${packageName}",`,
    "  factory: (require) => {",
    "    var module = { exports: {} };",
    "    var exports = module.exports;",
    body,
    "    return module.exports;",
    "  },",
    "});",
    "",
  ].join("\n"),
);

console.log("client bundle written to", path.relative(root, outfile));
